name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - v2
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_12_*_*_1
    - cron: "0 12 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the full history, to build attribution.json
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: yarn

      # Builds the modules, and boostraps the other modules
      - name: Build website
        run: |
          yarn install
          yarn docs-sync pull microsoft/TypeScript-Website-localizations#main 1
          yarn bootstrap
          yarn workspace typescriptlang-org setup-playground-cache-bust
          yarn build
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      - name: Makes the site
        run: |
          yarn build-site
          cp -r packages/typescriptlang-org/public site
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "site"
          skip_app_build: true

      # Update the site stats
      - run: node packages/typescriptlang-org/scripts/updateAppInsightsGitHubIssue.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
          APP_INSIGHTS_API_KEY: ${{ secrets.APP_INSIGHTS_API_KEY }}
          APP_INSIGHTS_ID: ${{ secrets.APP_INSIGHTS_ID }}
