name: Deploy to Vercel (Pre-built)

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
 

permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "vercel-deploy-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'ts-zh-docs/TypeScript-Website'

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Fetch the full history, to build attribution.json
          fetch-depth: 0
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      # Builds the modules, and bootstraps the other modules
      - name: Build website
        run: |
          pnpm install
          pnpm docs-sync pull ts-zh-docs/TypeScript-zh-Website#main 1
          pnpm bootstrap
          pnpm run --filter=typescriptlang-org setup-playground-cache-bust
          pnpm build

      - name: Build static site
        run: |
          pnpm build-site
          cp -r packages/typescriptlang-org/public site

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Configure Git for Vercel
        run: |
          git config --global user.email "awxiaoxian2020@163.com"
          git config --global user.name "GitHub Actions"

      # Push 到 v2 分支时部署到生产环境
      - name: Deploy to Vercel (Production)
        if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: vercel deploy ./site --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Pull Request 时部署预览版本
      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        run: vercel deploy ./site --token=${{ secrets.VERCEL_TOKEN }}
